name: bootmate
base: core24
version: '1.1.0'
summary: Manage autostart entries
description: |
  Boot Mate provides a simple and intuitive interface to manage your
  system's autostart entries. You can view all autostart applications,
  edit their properties, add startup parameters, or remove them entirely.

grade: stable
confinement: strict

apps:
  bootmate:
    command: usr/bin/bootmate
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - home
      - dot-config-autostart
      - system-autostart-read
      - desktop-applications-read
    slots:
      - dbus-bootmate
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      GTK_USE_PORTAL: "1"
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
      LOCPATH: $SNAP/usr/share/locale
      GTK_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-4.0

slots:
  dbus-bootmate:
    interface: dbus
    bus: session
    name: ch.srueegger.bootmate

plugs:
  dot-config-autostart:
    interface: personal-files
    write:
      - $HOME/.config/autostart
    read:
      - $HOME/.config/autostart

  system-autostart-read:
    interface: system-files
    read:
      - /etc/xdg/autostart
      - /usr/share/gnome/autostart

  desktop-applications-read:
    interface: system-files
    read:
      - /usr/share/applications
      - /var/lib/snapd/desktop/applications

parts:
  bootmate:
    plugin: nil
    source: .
    build-packages:
      - curl
      - gcc
      - meson
      - ninja-build
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev
      - libglib2.0-dev
      - libglib2.0-bin
      - gettext
      - desktop-file-utils
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libglib2.0-0
      - libglib2.0-bin
      - librsvg2-common
      - gsettings-desktop-schemas
      - libgdk-pixbuf-2.0-0
      - libpango-1.0-0
      - libcairo2
      - libgraphene-1.0-0
      - libgl1
      - libgl1-mesa-dri
      - libegl1
      - libglu1-mesa
      - mesa-vulkan-drivers
      - libvulkan1
      - locales-all
    override-build: |
      set -eux

      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
      source $HOME/.cargo/env

      # Build
      meson setup build --prefix=/usr -Dprofile=release
      ninja -C build
      DESTDIR=$CRAFT_PART_INSTALL ninja -C build install
