name: bootmate
base: core24
version: '1.1.0'
summary: Manage autostart entries
description: |
  Boot Mate provides a simple and intuitive interface to manage your
  system's autostart entries. You can view all autostart applications,
  edit their properties, add startup parameters, or remove them entirely.

  Perfect for managing which applications start automatically when you
  log in to your GNOME session.

  Features:
  - View all autostart entries from user and system directories
  - Edit autostart entry commands and parameters
  - Delete or disable autostart entries
  - Add new autostart entries from installed applications
  - Multi-language support (English and German)
  - Modern GNOME interface with libadwaita

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  bootmate:
    command: usr/local/bin/bootmate
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - home
      - dot-config-autostart
      - system-autostart-read
      - desktop-applications-read
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/usr/local/share:$XDG_DATA_DIRS
      GTK_USE_PORTAL: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

plugs:
  # Access to ~/.config/autostart for user autostart entries
  dot-config-autostart:
    interface: personal-files
    write:
      - $HOME/.config/autostart
    read:
      - $HOME/.config/autostart

  # Read-only access to system autostart directories
  system-autostart-read:
    interface: system-files
    read:
      - /etc/xdg/autostart
      - /usr/share/gnome/autostart

  # Read-only access to installed applications
  desktop-applications-read:
    interface: system-files
    read:
      - /usr/share/applications
      - /var/lib/snapd/desktop/applications

parts:
  bootmate:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr/local
      - -Dprofile=release
    # build-packages removed - installed manually before snapcraft in CI
    stage-packages:
      - libgtk-4-1
      - libadwaita-1-0
      - libglib2.0-0
      - libglib2.0-bin
      - librsvg2-common
      - gsettings-desktop-schemas
      - libcanberra-gtk3-module
    override-build: |
      craftctl default
      # Ensure proper permissions
      chmod +x $CRAFT_PART_INSTALL/usr/local/bin/bootmate || true
